name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Format YAMLs
      run: |
        gem install bundler:1.16.1
        bundle install --jobs 4 --retry 3
        bundle exec rails yaml_formatter:events yaml_formatter:songs yaml_formatter:venues
        git diff --exit-code
