name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Format YAMLs
      run: |
        gem install bundler:1.16.1 # TODO: Upgrade bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails yaml_formatter:events yaml_formatter:songs yaml_formatter:venues
        git diff db/*.yml --exit-code
    - name: Prompt to format
      uses: actions/github-script@v3
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Run `bundle exec rails yaml_formatter:events yaml_formatter:songs yaml_formatter:venues` before commit.'
          })
