name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Format YAMLs
      run: |
        gem install bundler:2.1.4
        bundle install --jobs 4 --retry 3
        bundle exec rails yaml:format:all
        git diff --exit-code db/*.yml
    - name: Prompt to format
      uses: actions/github-script@v3
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Run `bundle exec rails yaml:format:all` before commit.'
          })
